# Generated by Django 4.2.10 on 2024-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('intershipID', models.BigAutoField(primary_key=True, serialize=False)),
                ('organisation', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=200)),
                ('num_candidates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=300)),
            ],
        ),
    ]
