# Generated by Django 4.2.6 on 2024-02-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internships',
            new_name='Internship',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
