name: Django CI

# define workflow triggers and events 
on: [ push, pull_request, workflow_dispatch ]

jobs:

  # build the application
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name : Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

  # run application tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Django testing
        run: |
          python manage.py test
        working-directory: SkillPilot-CS3528

  # deploy application 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy feature
        run: echo "Deploying app with new feature..."