name: Django Github Action

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v3 
      - name: Setup Python Version ${{ matrix.python-version }} 
        uses: actions/setup-python@v4.1.0 # use the built-in action for setting up python projects
        with:
          # apply setup action with version of python currently used by the matrix
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Linting process - ensure code quality 
      - name: Lint with flake8
        run: |
          flake8 .

      - name: Run tests
        run: |
          python manage.py collectstatic
          python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy application to Heroku

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # action from marketplace to deploy to heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "m.diprofio.21@abdn.ac.uk"
          branch: "main"