name: Django CI

# define workflow triggers and events 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:

  # build the application
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      # matrix-build - run the same build using the matrix strategy for python version 3.7
      matrix: 
        python-version: [ 3.9 ]

    steps:
      - name: Fetch repository code
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name : Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # run application tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          cd ..
          python manage.py test

  # deploy application 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy feature
        run: echo "Deploying app with new feature..."