name: Integrate Feature via Pull Request
on:
  pull_request:
    types:
      - opened
    branches:
      - 'feature/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "Installing dependencies..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test application
        run: echo "Testing application..."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy feature
        run: echo "Deploying app with new feature..."